### ISSUE TITLE
Detect and process escape and enter

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#1]
Hi,

How do you detect keypresses for escape and enter to end editing and either save or cancel the changes?  I am new to Ember so I might just not know how to do it...  If not possible, I would like to request it as a feature.

tried escape-press='alertUser' without success.

Thanks!

**Comment by chrissloey** [comment]
I had a try and it's not currently possible - adding support for it now :smile:

**Comment by chrissloey** [comment]
Released 0.2.0 which should fix this, just update the version in your package.json and do an `npm install` and both `escape-press='alertUser'` and `enter='otherEvent'` should work.

Let me know i you have any more issues :)

**Comment by friksa** [comment]
This is an amazing add-on!  Well done and thank you so much!  Also very impressed with the response times :)

Tested both escape-press and enter attributes and they work as advertised.

**Comment by friksa** [comment]
When I look at:
https://github.com/emberjs/ember.js/blob/v1.13.6/packages/ember-views/lib/mixins/text_support.js

Ember includes this so that you can get a reference back to the input. See line 236.
sendAction('escape-press', this, event);

On escape, I need to stop editing and lose focus and undo changes and it will help to get a reference to this.

Thanks!

**Comment by friksa** [comment]
Actually, I see that this file implemented sendAction differently... and they only pass currentValue.  I think it is important to be consistent with the Ember implementation.. but it might make sense to add currentValue first and then also a reference to the contentEditable... unless there is a better way to accomplish what I am trying to do.

**Comment by chrissloey** [comment]
Oops yeah you're definitely right about keeping consistent with the Ember implementation. I'll update later to match their params / happy to accept a PR before then too.

**Comment by chrissloey** [comment]
Ok, params now match those from TextSupport like you pointed out.

For the current value you wanted, could you just use `contentEditable.get('value')`, where `contentEditable` is the first param to `escape-press`?

Hope that helps.

**Comment by friksa** [comment]
Thanks - i am all set with this one.
