### ISSUE TITLE
Reflecting model changes

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#2]
When the bound model changes, it is not reflected in this component.  It needs something like this to behave consistent with other components:

  itemChanged: function() {
    try {
      this.$().html(this.get('value'));
    } catch(err){}
  }.observes('value'),

**Comment by chrissloey** [comment]
Thanks, fixed in 0.2.4 :)

**Comment by chrissloey** [comment]
This introduced another bug - reopening for now.

**Comment by chrissloey** [comment]
Fixed the bug that was introduced here in 0.3
