### ISSUE TITLE
Can you provide documentation or tests on how to Acceptance Test this?

### ISSUE THREAD

**Issue by aronysidoro** [AddJam/ember-content-editable#24]
I've been trying to set up an Acceptance Test with `content-editable` but am having issues.

I'm sure this may be as easy as jQuery focus in, add text, focus out.  But, just can't seem to get it working, so some example docs or tests would be great.

Thanks

**Comment by Gaurav0** [comment]
It might be a good idea to get the 'fillIn' helper to automatically handle content-editable.

**Comment by Gaurav0** [comment]
Also, writing an acceptance test for the dummy app would be extremely helpful.
