### ISSUE TITLE
Value gets out of sync with html view

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#4]
When you press enter, the value does not match what is seen in the browser (value may not have the line feed where it is in the browser).  Found this workaround to keep them in sync.

```javascript
  updateValue: Ember.on('keyUp', function(event) {
    this.handleKeyUp(event);
    var v=this.stringInterpolator(this.$().text());
    this.set('value', v);
    this.$().html(v);
  }),
````

**Comment by chrissloey** [comment]
Was this a problem with 0.2.4? I introduced a bug there that sounds similar to this. Can you check if 0.3.0 fixed this?

**Comment by friksa** [comment]
have not tested it with new updates... will test it and report back

**Comment by friksa** [comment]
tested the latest build and not an issue.  Awesome job!
