### ISSUE TITLE
Initial empty field collapses on FireFox on the mac

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#5]
When editing an empty string value on FireFox (Mac), the height of the div collapses by about 70%.  If you add text, it is normal size... then if you delete all the text, it is still fine.  This issue was recreated with isText=true.

The css below fixes the issue.  One day I will figure out how to do pull requests and start contributing that way, but for now, here is my fix.  :)
````
.ember-content-editable:empty::after {
  content: "\0000a0";
}
````

**Comment by chrissloey** [comment]
Added your fix :)

Pull requests are actually pretty straightforward once you've done it a couple of times, decent guide [here](https://help.github.com/articles/using-pull-requests/) :smile:
