### ISSUE TITLE
Watermark color incorrect

### ISSUE THREAD

**Issue by friksa** [AddJam/ember-content-editable#6]
The placeholder color should not be modified as it is too hard to override in app.css.

Preferably it should be provided as a property that can be set with a default value of #cccccc.
````
[contenteditable=true]:empty:not(:focus):before {
  content: attr(placeholder);
  color: rgba(0,0,0,0.6);//remove this line or use attr(watermarkcolor)
}
````

By not specifying it, I can override it more easily in app.css
````
.ember-content-editable:empty {
  color: #cccccc;
}
````

**Comment by chrissloey** [comment]
Thanks, I've moved where it is specified to match your second block of code - that way the default styling can remain and overriding it is simple :)

Fix is in 0.3.2.
