### ISSUE TITLE
Alias for contenteditable

### ISSUE THREAD

**Issue by jevanlingen** [AddJam/ember-content-editable#7]
Just tried your add on, works great! I was wondering, would you consider to add `editable` as an alias for the `contenteditable` property?

I think this:

```javascript
{{content-editable value=model.myValue editable=model.editMode}}
````

looks nicer than:

```javascript
{{content-editable value=model.myValue contenteditable=model.editMode}}
```

**Comment by chrissloey** [comment]
I like it, it's in 0.3.6. Thanks :smile:

**Comment by jevanlingen** [comment]
Wow quick response! Thank you very much.
